---
- hosts: zabbix
  remote_user: root
  vars:
    zabbix_server: 192.168.200.141
  tasks:
    - name: Install zabbix-agent CentOS 6 Source
      yum: 
        name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS"  and  ansible_distribution_major_version == "6"
      
    - name: Install zabbix-agent CentOS 7 yum Source
      yum: 
        name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS"  and  ansible_distribution_major_version == "7"
    
    - name: Install zabbix-agent
      yum:
        name: zabbix-agent
        state: present
        
    - name: Copy zabbix agent  configuration file
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        
    - name: start zabbix agent
      service:
        name: zabbix-agent
        state: started
        enabled: true